# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    _instanceof:
        App\Modules\Shared\Domain\Bus\Command\CommandHandler:
            tags: [ 'internal.command_handler' ]
        App\Modules\Shared\Domain\Bus\Query\QueryHandler:
            tags: [ 'internal.query_handler' ]

    App\Modules\Shared\Infrastructure\Bus\Command\InMemoryCommandBus:
        class: App\Modules\Shared\Infrastructure\Bus\Command\InMemoryCommandBus
        arguments: [ !tagged internal.command_handler ]
    App\Modules\Shared\Infrastructure\Bus\Query\InMemoryQueryBus:
        class: App\Modules\Shared\Infrastructure\Bus\Query\InMemoryQueryBus
        arguments: [ !tagged internal.query_handler ]

    App\Modules\Order\Application\Discounts\OrderOverThousandDiscount:
    App\Modules\Order\Application\Discounts\SwitchesDiscount:
        arguments:
            $queryBus: '@App\Modules\Shared\Infrastructure\Bus\Query\InMemoryQueryBus'
    App\Modules\Order\Application\Discounts\ToolsDiscount:
        arguments:
            $queryBus: '@App\Modules\Shared\Infrastructure\Bus\Query\InMemoryQueryBus'

    App\Modules\Order\Infrastructure\Discounts\OrderDiscountsApplier:
        class: App\Modules\Order\Infrastructure\Discounts\OrderDiscountsApplier
        arguments:
            $discounts: [
                '@App\Modules\Order\Application\Discounts\OrderOverThousandDiscount',
                '@App\Modules\Order\Application\Discounts\SwitchesDiscount',
                '@App\Modules\Order\Application\Discounts\ToolsDiscount'
            ]
        
    App\Modules\Order\UI\Controller\DiscountsController:
        arguments:
            $bus: '@App\Modules\Shared\Infrastructure\Bus\Command\InMemoryCommandBus'
